apiVersion: v2
name: my-tomcat-app
description: A Helm chart for deploying Tomcat with blue-green deployment strategy
version: 0.1.0
appVersion: "1.0"
keywords:
  - tomcat
  - java
  - webserver
maintainers:
  - name: John Doe
    email: john.doe@example.com
home: https://example.com/my-tomcat-app
sources:
  - https://github.com/example/my-tomcat-app
dependencies:
  - name: database-chart
    version: 1.0.0
    repository: https://charts.example.com
